concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Ansible control node"
  url = "https://gitlab.com/"
  token = "<insert runner token>"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "centos:7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:rw", "/etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:rw", "/home/ansible/ssl:/etc/nginx/ssl:rw", "/home/ansible/conf.d:/etc/nginx/conf.d:rw"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "ansible-node-shell"
  url = "https://gitlab.com/"
  token = "<insert runner token>"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]